image: pikalab/ci:ubuntu-jdk14-git-gradle-graphviz

variables:
  GOPTS: "--no-daemon --console=plain"
  CI: "true"
  BEFORE_TASK: ""
  AFTER_TASK: ""
  GCMD: "gradle"
  BUILD_TASK: "clean assemble"
  TEST_TASK: "check"
  TEST_JVM_TASK: "jvmTest"
  TEST_JS_TASK: "clean jsTest"
  BINTRAY_TASK: "publishAllToBintray"
  CENTRAL_TASK: "publishAllPublicationsToMavenRepository"
  JS_COMPILE_TASK: "clean jsMain"
  NPM_PUBLISH_TASK: "npmPublish"
  GITHUB_PUBLISH_TASK: "githubRelease"
  PAGES_TASK: "orchidBuild"
  ORG_GRADLE_PROJECT_orchidBaseUrl: "https://pika-lab.gitlab.io/tuprolog/2p-in-kotlin/"

before_script:
  - chmod +x gradlew
  - source $HOME/.sdkman/bin/sdkman-init.sh

cache:
  paths:
    - $HOME/.gradle/
    - gradle/
    - .gradle/
    - build/

Compile:
  stage: build
  script: $GCMD $BEFORE_TASK $BUILD_TASK $AFTER_TASK $GOPTS

Test JVM:
  stage: test
  script: $GCMD $BEFORE_TASK $TEST_JVM_TASK $AFTER_TASK $GOPTS
  artifacts:
    reports:
      junit: "**/build/test-results/jvmTest/*.xml"

Test JS:
  stage: test
  script: $GCMD $BEFORE_TASK $TEST_JS_TASK $AFTER_TASK $GOPTS

Deploy to Bintray:
  stage: deploy
  script: $GCMD $BEFORE_TASK $BINTRAY_TASK $AFTER_TASK $GOPTS
  environment:
    name: Bintray
    url: "https://bintray.com/pika-lab/tuprolog"
  only:
    - /^(master)|(release)|(develop)$/

Deploy to Maven Central:
  stage: deploy
  script: $GCMD $BEFORE_TASK $CENTRAL_TASK $AFTER_TASK $GOPTS
  environment:
    name: Maven Central
    url: "https://oss.sonatype.org"
  only:
    - /^(master)|(release)$/

Deploy to NPM:
  stage: deploy
  script:
    - $GCMD $BEFORE_TASK $JS_COMPILE_TASK $AFTER_TASK $GOPTS
    - $GCMD $BEFORE_TASK $NPM_PUBLISH_TASK $AFTER_TASK $GOPTS
  environment:
    name: NPM
    url: "https://www.npmjs.com/org/tuprolog"
  only:
    - /^(master)|(release)|(develop)$/

Deploy to GitHub:
  stage: deploy
  script:
    - $GCMD $BEFORE_TASK $GITHUB_PUBLISH_TASK $AFTER_TASK $GOPTS
  environment:
    name: GitHub
    url: "https://github.com/tuProlog/2p-kt/releases"
  only:
    - /^(master)|(release)|(develop)$/

pages:
  script:
    - mkdir public
    - $GCMD $BEFORE_TASK $PAGES_TASK $AFTER_TASK $GOPTS
    - cp -r documentation/build/docs/orchid/* public
  artifacts:
    paths:
      - public
  allow_failure: true
  only:
    - /^(master)|(release)|(documentation)$/
